Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,76 +32,78 @@ jobs:
       ENDORCTL_VERSION: "latest"
       ENDOR_NAMESPACE: "yolo"
       DEBUG: "false"
-    - when:
-        condition:
-          equal: [ main, << pipeline.git.branch >> ]
-        steps:
-          - checkout
-          - attach_workspace:
-              at: .
-          - restore_cache:
-              keys:
-                # when lock file changes, use increasingly general patterns to restore cache
-                - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
-                - maven-repo-v1-{{ .Branch }}-
-                - maven-repo-v1-
-          - run:
-              name: "Install endorctl"
-              command: |
-                apt-get update && apt-get install -y jq
-                if [ "$ENDORCTL_VERSION" == "latest" ]; then
-                  echo "Downloading latest version of endorctl"
-                  VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
-                  ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
-                  curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
-                  echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
-                  if [ $? -ne 0 ]; then
-                    echo "Integrity check failed"
-                    exit 1
+    steps:
+      - when:
+          condition:
+            equal: [ main, << pipeline.git.branch >> ]
+          steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - restore_cache:
+                keys:
+                  # when lock file changes, use increasingly general patterns to restore cache
+                  - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
+                  - maven-repo-v1-{{ .Branch }}-
+                  - maven-repo-v1-
+            - run:
+                name: "Install endorctl"
+                command: |
+                  apt-get update && apt-get install -y jq
+                  if [ "$ENDORCTL_VERSION" == "latest" ]; then
+                    echo "Downloading latest version of endorctl"
+                    VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
+                    ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
+                    curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
+                    echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
+                    if [ $? -ne 0 ]; then
+                      echo "Integrity check failed"
+                      exit 1
+                    fi
+                  else
+                    echo "Downloading version $ENDORCTL_VERSION of endorctl"
+                    curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
+                    # You need to set ENDORCTL_SHA here if you are using it in the integrity check
                   fi
-                else
-                  echo "Downloading version $ENDORCTL_VERSION of endorctl"
-                  curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
-                  # You need to set ENDORCTL_SHA here if you are using it in the integrity check
-                fi
-                chmod +x ./endorctl
-                ./endorctl --version
-                ./endorctl scan --enable=git,analytics,secrets
-    - when:
-        condition:
-          not_equal: [ main, << pipeline.git.branch >> ]
-        steps:
-          - checkout
-          - attach_workspace:
-              at: .
-          - restore_cache:
-              keys:
-                # when lock file changes, use increasingly general patterns to restore cache
-                - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
-                - maven-repo-v1-{{ .Branch }}-
-                - maven-repo-v1-
-          - run:
-              name: "Install endorctl"
-              command: |
-                apt-get update && apt-get install -y jq
-                if [ "$ENDORCTL_VERSION" == "latest" ]; then
-                  echo "Downloading latest version of endorctl"
-                  VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
-                  ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
-                  curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
-                  echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
-                  if [ $? -ne 0 ]; then
-                    echo "Integrity check failed"
-                    exit 1
+                  chmod +x ./endorctl
+                  ./endorctl --version
+                  ./endorctl scan --enable=git,analytics,secrets
+      - when:
+          condition:
+            not_equal: [ main, << pipeline.git.branch >> ]
+          steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - restore_cache:
+                keys:
+                  # when lock file changes, use increasingly general patterns to restore cache
+                  - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
+                  - maven-repo-v1-{{ .Branch }}-
+                  - maven-repo-v1-
+            - run:
+                name: "Install endorctl"
+                command: |
+                  apt-get update && apt-get install -y jq
+                  if [ "$ENDORCTL_VERSION" == "latest" ]; then
+                    echo "Downloading latest version of endorctl"
+                    VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
+                    ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
+                    curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
+                    echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
+                    if [ $? -ne 0 ]; then
+                      echo "Integrity check failed"
+                      exit 1
+                    fi
+                  else
+                    echo "Downloading version $ENDORCTL_VERSION of endorctl"
+                    curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
+                    # You need to set ENDORCTL_SHA here if you are using it in the integrity check
                   fi
-                else
-                  echo "Downloading version $ENDORCTL_VERSION of endorctl"
-                  curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
-                  # You need to set ENDORCTL_SHA here if you are using it in the integrity check
-                fi
-                chmod +x ./endorctl
-                ./endorctl --version
-                ./endorctl scan --enable=git,analytics,secrets --ci-run --ci-baseline=main
+                  chmod +x ./endorctl
+                  ./endorctl --version
+                  ./endorctl scan --enable=git,analytics,secrets --ci-run --ci-baseline=main
+
 workflows:
   build_and_test:
     jobs:
